#!/bin/bash
SRC=$1
shift 1
EXE=$1
shift 1
ARGS=$*
docker exec --privileged --user root vaccs sysctl -w kernel.yama.ptrace_scope=0
docker exec --privileged --user root vaccs sysctl -w kernel.randomize_va_space=0
docker cp $SRC vaccs:/home/vaccs/$SRC
docker exec --user vaccs vaccs analyze $SRC /home/vaccs/$EXE $ARGS
docker cp vaccs:/home/vaccs/$EXE.vaccs $EXE.vaccs
